import type { Metadata } from "next";
import "./globals.css";
import { Fredoka, Quicksand } from "next/font/google";
import { NavBar } from "@/components/layout/NavBar";

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${quicksand.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
